/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Animation.Animation;
import Object.Truck;
import Object.Windmill;
import Shapes2D.Circle;
import Shapes2D.Ellipse;
import Shapes2D.Line;
import Shapes2D.Pencil;
import Shapes2D.Rectangle;
import Shapes2D.Shape2D;
import Shapes2D.Transform;
import Shapes2D.Triangle;
import Shapes3D.HinhCau;
import Shapes3D.HinhHop;
import Shapes3D.HinhNon;
import View.Coordinate;
import View.Coordinate3D;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Stack;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Lương Vĩ Phú
 */
public class Display extends javax.swing.JFrame {
    
    /**
     * Creates new form TEST
     */
    
    private Point moveStart;
    private Point start, end;
    private String mode = "";
    private String object = "";
    private ArrayList<Shape2D> paint2D = new ArrayList<>();
    private Stack<Shape2D> stack = new Stack<>();
    private int size=5; // cỡ nét vẽ
    private Color color;// set màu cơ bản
    Timer time;
    int delay=100;
    boolean running;
    float angle = 0;
    int speed;
    int flag;
    
    // Init Shape2D
    private Line line;
    private Rectangle rect;
    private Pencil pen;
    private Triangle triangle;
    private Circle circle;
    private Ellipse elip;
    private Windmill wm;
    private Truck t;
    private Animation ani = new Animation();
    
    public Display() {
        initComponents();
        panel3D.setVisible(false);
        panelObj.setVisible(false);
        panel2D.setVisible(true);
        panelAni.setVisible(false);
        rb2D.setSelected(true);
        butPlayStop.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public int ConvertX(int coor){
        return coor * size + panelDrawingArea.getWidth()/2;
    }
    
    public int ConvertY(int coor){
        return (-coor) * size + panelDrawingArea.getHeight()/2;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
        if(cbGrid.isSelected()){
            new Coordinate().drawGrid(panelDrawingArea, panelDrawingArea.getGraphics());
        }
        if(cbCoordinate.isSelected() && rb2D.isSelected()){
            new Coordinate().drawCoor(panelDrawingArea, panelDrawingArea.getGraphics());
        }else if(cbCoordinate.isSelected() && rb3D.isSelected()){
            new Coordinate3D().drawCoor(panelDrawingArea, panelDrawingArea.getGraphics());
        }
        
        // Vẽ hình 2d
        if(constraint2D() == true){
            if(butLine.isSelected()){
                if (cbCustomLine.getSelectedItem().toString().equals("DEFAULT")) {
                    line = new Line();
                    line.init(start, end, size, color);
                    line.draw(panelDrawingArea.getGraphics());
                    line.Axis(start, end, panelDrawingArea.getGraphics());
                    paint2D.add(line);
                } else if (cbCustomLine.getSelectedItem().toString().equals("DASH")) {
                    line = new Line();
                    line.init(start, end, size, color);
                    line.dashedLine(panelDrawingArea.getGraphics());
                    line.Axis(start, end, panelDrawingArea.getGraphics());
                    paint2D.add(line);
                } else if (cbCustomLine.getSelectedItem().toString().equals("DOT")) {
                    line = new Line();
                    line.init(start, end, size, color);
                    line.dotLine(panelDrawingArea.getGraphics());
                    line.Axis(start, end, panelDrawingArea.getGraphics());
                    paint2D.add(line);
                } else if (cbCustomLine.getSelectedItem().toString().equals("DASHDOT")) {
                    line = new Line();
                    line.init(start, end, size, color);
                    line.dashedDotLine(panelDrawingArea.getGraphics());
                    line.Axis(start, end, panelDrawingArea.getGraphics());
                    paint2D.add(line);
                } else if (cbCustomLine.getSelectedItem().toString().equals("DASHDOTDOT")) {
                    line = new Line();
                    line.init(start, end, size, color);
                    line.dashedDotDotLine(panelDrawingArea.getGraphics());
                    line.Axis(start, end, panelDrawingArea.getGraphics());
                    paint2D.add(line);
                } else if (cbCustomLine.getSelectedItem().toString().equals("ARROW")) {
                    line = new Line();
                    line.init(start, end, size, color);
                    line.arrowLine(panelDrawingArea.getGraphics());
                    line.Axis(start, end, panelDrawingArea.getGraphics());
                    paint2D.add(line);
                }
            }else if(butRectangle.isSelected()){
                rect = new Rectangle();
                rect.init(start, end, size, color);
                rect.draw(panelDrawingArea.getGraphics());
                rect.Axis(start,end,panelDrawingArea.getGraphics());
                paint2D.add(rect);
            }else if(butCircle.isSelected()){
                circle = new Circle();
                circle.init(start, end, size, color);
                circle.draw(panelDrawingArea.getGraphics());
                circle.Axis(panelDrawingArea.getGraphics()); 
                paint2D.add(circle);
            }else if(butTriangle.isSelected()){
                triangle = new Triangle();
                triangle.init(end, start, size, color);
                triangle.draw(panelDrawingArea.getGraphics());
                triangle.Axis(start,end,panelDrawingArea.getGraphics());
                paint2D.add(triangle);                
            }else if(butEllipse.isSelected()){
                elip = new Ellipse();
                elip.init(start, end, size, color);
                elip.draw(panelDrawingArea.getGraphics());
                elip.Axis(panelDrawingArea.getGraphics());
                paint2D.add(elip);                
            }
        }
        
        // Vẽ vật
        if(constraintObj()){
            if(object.equals("Truck")){
                if (butMove.isSelected()) {
                    t.drawTran(panelDrawingArea.getGraphics(),Integer.parseInt(tfNewX.getText())*size, -Integer.parseInt(tfNewY.getText())*size);
                } else if (butScaling.isSelected()) {
                    t.drawScale(panelDrawingArea.getGraphics(), Float.parseFloat(tfNewX.getText()), Float.parseFloat(tfNewY.getText()));
                } else if (butRotation.isSelected()) {
                    t.drawRotate(panelDrawingArea.getGraphics(), Float.parseFloat(tfNewCorner.getText()));;
                }
                lbHienThiThongTin.setText(t.showCoor());
            }else if(object.equals("Windmill")){
                if (butMove.isSelected()) {
                    wm.drawTran(panelDrawingArea.getGraphics(),Integer.parseInt(tfNewX.getText()), Integer.parseInt(tfNewY.getText()));
                } else if (butScaling.isSelected()) {
                    wm.drawScale(panelDrawingArea.getGraphics(), Float.parseFloat(tfNewX.getText()), Float.parseFloat(tfNewY.getText()));
                } else if (butRotation.isSelected()) {
                    wm.drawRotate(panelDrawingArea.getGraphics(), Float.parseFloat(tfNewCorner.getText()));;
                }
                lbHienThiThongTin.setText(wm.showCoor());
            }
        }else{
            if (object.equals("Truck")) {
                t.init();
                t.draw(panelDrawingArea.getGraphics());
            } else if (object.equals("Windmill")) {
                wm.init();
                wm.draw(panelDrawingArea.getGraphics());
            }
        }
        
        if(butReflX.isSelected()){
            if(object.equals("Truck")){
                t.drawRefX(panelDrawingArea.getGraphics());
                bgObject.clearSelection();
            }else if(object.equals("Windmill")){
                wm.drawRefX(panelDrawingArea.getGraphics());
                bgObject.clearSelection();
            }
        } else if (butReflY.isSelected()) {
            if(object.equals("Truck")){
                t.drawRefY(panelDrawingArea.getGraphics());
                bgObject.clearSelection();
            }else if(object.equals("Windmill")){
                wm.drawRefY(panelDrawingArea.getGraphics());
                bgObject.clearSelection();
            }
        }else if (butReflO.isSelected()) {
            if(object.equals("Truck")){
                t.drawRefO(panelDrawingArea.getGraphics());
                bgObject.clearSelection();
            }else if(object.equals("Windmill")){
                wm.drawRefO(panelDrawingArea.getGraphics());
                bgObject.clearSelection();
            }
        }
        
        // Vẽ hình 3d
        Graphics2D g2d = (Graphics2D) panelDrawingArea.getGraphics();
        if (constraint3D() == true) {
            if (butCube.isSelected()) {
                HinhHop hh = new HinhHop();
                hh.setColor(color);
                hh.setX(Integer.parseInt(tf3D_X.getText()));
                hh.setY(Integer.parseInt(tf3D_y.getText()));
                hh.setZ(Integer.parseInt(tf3D_Z.getText()));
                hh.setDai(Integer.parseInt(tf3D_Dai.getText()));
                hh.setRong(Integer.parseInt(tf3D_Rong.getText()));
                hh.setCao(Integer.parseInt(tf3D_Cao.getText()));
                hh.draw(g2d);
            } else if (butSphere.isSelected()) {
                HinhCau hc = new HinhCau();
                hc.setColor(color);
                hc.setX(Integer.parseInt(tf3D_X.getText()));
                hc.setY(Integer.parseInt(tf3D_y.getText()));
                hc.setZ(Integer.parseInt(tf3D_Z.getText()));
                hc.setR(Integer.parseInt(tf3D_Dai.getText()));
                hc.draw(g2d);
            } else if (butCone.isSelected()) {
                HinhNon hn = new HinhNon();
                hn.setColor(color);
                hn.setX(Integer.parseInt(tf3D_X.getText()));
                hn.setY(Integer.parseInt(tf3D_y.getText()));
                hn.setZ(Integer.parseInt(tf3D_Z.getText()));
                hn.setR(Integer.parseInt(tf3D_Dai.getText()));
                hn.setCao(Integer.parseInt(tf3D_Cao.getText()));
                hn.draw(g2d);
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_ = new javax.swing.ButtonGroup();
        bg2D = new javax.swing.ButtonGroup();
        bg3D = new javax.swing.ButtonGroup();
        bgObject = new javax.swing.ButtonGroup();
        dialogTruck = new javax.swing.JDialog();
        panelTruck = new javax.swing.JPanel();
        tfOX = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfOY = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfSize = new javax.swing.JTextField();
        butPaintTruck = new javax.swing.JButton();
        dialogWindmill = new javax.swing.JDialog();
        panelWindmill = new javax.swing.JPanel();
        tfOXWm = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfOYWm = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfSizeWm = new javax.swing.JTextField();
        butPaintWm = new javax.swing.JButton();
        dialogCoor = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbHienThiThongTin = new javax.swing.JTextArea();
        panelDrawing = new javax.swing.JPanel();
        panelDrawingArea = new javax.swing.JPanel();
        panelSetUp = new javax.swing.JPanel();
        panel2D = new javax.swing.JPanel();
        panel2DStart = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf2D_SX = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf2D_SY = new javax.swing.JTextField();
        panel2DEnd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf2D_EX = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf2D_EY = new javax.swing.JTextField();
        panel2DShape = new javax.swing.JPanel();
        butLine = new javax.swing.JToggleButton();
        butRectangle = new javax.swing.JToggleButton();
        butTriangle = new javax.swing.JToggleButton();
        butCircle = new javax.swing.JToggleButton();
        butEllipse = new javax.swing.JToggleButton();
        but2DPaint = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panel3D = new javax.swing.JPanel();
        panel3DInput = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf3D_Dai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf3D_y = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf3D_Cao = new javax.swing.JTextField();
        tf3D_Rong = new javax.swing.JTextField();
        tf3D_Z = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf3D_X = new javax.swing.JTextField();
        panel3DShape = new javax.swing.JPanel();
        butSphere = new javax.swing.JToggleButton();
        butCube = new javax.swing.JToggleButton();
        butCone = new javax.swing.JToggleButton();
        but3DPaint = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        panelObj = new javax.swing.JPanel();
        panelTransform = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tfNewX = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfNewY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNewCorner = new javax.swing.JTextField();
        butMove = new javax.swing.JToggleButton();
        butScaling = new javax.swing.JToggleButton();
        butRotation = new javax.swing.JToggleButton();
        butReflX = new javax.swing.JToggleButton();
        butReflY = new javax.swing.JToggleButton();
        butReflO = new javax.swing.JToggleButton();
        panelComponent = new javax.swing.JPanel();
        butShowCo = new javax.swing.JButton();
        butTransform = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        panelAni = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbCoAni = new javax.swing.JTextArea();
        panelOperation = new javax.swing.JPanel();
        butOpenFile = new javax.swing.JButton();
        butSave = new javax.swing.JButton();
        panelHead = new javax.swing.JPanel();
        panelTool = new javax.swing.JPanel();
        cbCustomLine = new javax.swing.JComboBox<>();
        butClean = new javax.swing.JButton();
        cbCoordinate = new javax.swing.JCheckBox();
        cbGrid = new javax.swing.JCheckBox();
        rb2D = new javax.swing.JRadioButton();
        rb3D = new javax.swing.JRadioButton();
        butColour = new javax.swing.JButton();
        panelObject = new javax.swing.JPanel();
        butTruck = new javax.swing.JButton();
        butWindmill = new javax.swing.JButton();
        panelAnimation = new javax.swing.JPanel();
        butAnimationTruck = new javax.swing.JButton();
        butPlayStop = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        panelTruck.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Truck", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel15.setText("Point  O");

        jLabel16.setText("X:");

        jLabel17.setText("Y:");

        jLabel18.setText("Size:");

        butPaintTruck.setText("Paint");
        butPaintTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPaintTruckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTruckLayout = new javax.swing.GroupLayout(panelTruck);
        panelTruck.setLayout(panelTruckLayout);
        panelTruckLayout.setHorizontalGroup(
            panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTruckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butPaintTruck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTruckLayout.createSequentialGroup()
                        .addGroup(panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSize, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(tfOX))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTruckLayout.setVerticalGroup(
            panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTruckLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(tfOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfOY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butPaintTruck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogTruckLayout = new javax.swing.GroupLayout(dialogTruck.getContentPane());
        dialogTruck.getContentPane().setLayout(dialogTruckLayout);
        dialogTruckLayout.setHorizontalGroup(
            dialogTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTruckLayout.createSequentialGroup()
                .addComponent(panelTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogTruckLayout.setVerticalGroup(
            dialogTruckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTruck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelWindmill.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Windmill", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel20.setText("X:");

        jLabel21.setText("Y:");

        jLabel22.setText("Size:");

        butPaintWm.setText("Paint");
        butPaintWm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPaintWmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWindmillLayout = new javax.swing.GroupLayout(panelWindmill);
        panelWindmill.setLayout(panelWindmillLayout);
        panelWindmillLayout.setHorizontalGroup(
            panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWindmillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butPaintWm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelWindmillLayout.createSequentialGroup()
                        .addGroup(panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20))
                        .addGap(20, 20, 20)
                        .addGroup(panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfOXWm)
                            .addComponent(tfSizeWm, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOYWm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelWindmillLayout.setVerticalGroup(
            panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWindmillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfOXWm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfOYWm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfSizeWm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butPaintWm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogWindmillLayout = new javax.swing.GroupLayout(dialogWindmill.getContentPane());
        dialogWindmill.getContentPane().setLayout(dialogWindmillLayout);
        dialogWindmillLayout.setHorizontalGroup(
            dialogWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogWindmillLayout.createSequentialGroup()
                .addComponent(panelWindmill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogWindmillLayout.setVerticalGroup(
            dialogWindmillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWindmill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogCoor.setTitle("Show Coordinate");

        lbHienThiThongTin.setColumns(20);
        lbHienThiThongTin.setRows(5);
        jScrollPane1.setViewportView(lbHienThiThongTin);

        javax.swing.GroupLayout dialogCoorLayout = new javax.swing.GroupLayout(dialogCoor.getContentPane());
        dialogCoor.getContentPane().setLayout(dialogCoorLayout);
        dialogCoorLayout.setHorizontalGroup(
            dialogCoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        dialogCoorLayout.setVerticalGroup(
            dialogCoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vẽ - san");
        setResizable(false);

        panelDrawing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDrawingMouseClicked(evt);
            }
        });

        panelDrawingArea.setBackground(new java.awt.Color(255, 255, 255));
        panelDrawingArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDrawingArea.setPreferredSize(new java.awt.Dimension(990, 500));
        panelDrawingArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelDrawingAreaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelDrawingAreaLayout = new javax.swing.GroupLayout(panelDrawingArea);
        panelDrawingArea.setLayout(panelDrawingAreaLayout);
        panelDrawingAreaLayout.setHorizontalGroup(
            panelDrawingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDrawingAreaLayout.setVerticalGroup(
            panelDrawingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        panelSetUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2D.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        panel2DStart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Start", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel4.setText("X:");

        jLabel5.setText("Y:");

        javax.swing.GroupLayout panel2DStartLayout = new javax.swing.GroupLayout(panel2DStart);
        panel2DStart.setLayout(panel2DStartLayout);
        panel2DStartLayout.setHorizontalGroup(
            panel2DStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DStartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_SX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_SY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2DStartLayout.setVerticalGroup(
            panel2DStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DStartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf2D_SX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf2D_SY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2DEnd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "End", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel2.setText("X:");

        jLabel3.setText("Y:");

        javax.swing.GroupLayout panel2DEndLayout = new javax.swing.GroupLayout(panel2DEnd);
        panel2DEnd.setLayout(panel2DEndLayout);
        panel2DEndLayout.setHorizontalGroup(
            panel2DEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DEndLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_EX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2D_EY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2DEndLayout.setVerticalGroup(
            panel2DEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf2D_EX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf2D_EY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2DShape.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shape", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        bg2D.add(butLine);
        butLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Line.png"))); // NOI18N

        bg2D.add(butRectangle);
        butRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rectangle.png"))); // NOI18N

        bg2D.add(butTriangle);
        butTriangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/triangle.png"))); // NOI18N

        bg2D.add(butCircle);
        butCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/circle.png"))); // NOI18N

        bg2D.add(butEllipse);
        butEllipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ellipse.png"))); // NOI18N

        javax.swing.GroupLayout panel2DShapeLayout = new javax.swing.GroupLayout(panel2DShape);
        panel2DShape.setLayout(panel2DShapeLayout);
        panel2DShapeLayout.setHorizontalGroup(
            panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2DShapeLayout.createSequentialGroup()
                        .addComponent(butLine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2DShapeLayout.createSequentialGroup()
                        .addComponent(butTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(butEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2DShapeLayout.setVerticalGroup(
            panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        but2DPaint.setText("Paint");
        but2DPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2DPaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2DLayout = new javax.swing.GroupLayout(panel2D);
        panel2D.setLayout(panel2DLayout);
        panel2DLayout.setHorizontalGroup(
            panel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panel2DShape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but2DPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel2DEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel2DStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2DLayout.setVerticalGroup(
            panel2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2DStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2DEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but2DPaint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSetUp.add(panel2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        panel3D.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "3D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        panel3DInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel6.setText("X:");

        jLabel1.setText("Z:");

        jLabel12.setText("Rộng:");

        jLabel7.setText("Y:");

        jLabel13.setText("Cao:");

        jLabel11.setText("Dài:");

        javax.swing.GroupLayout panel3DInputLayout = new javax.swing.GroupLayout(panel3DInput);
        panel3DInput.setLayout(panel3DInputLayout);
        panel3DInputLayout.setHorizontalGroup(
            panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DInputLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf3D_X, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(tf3D_Z)
                    .addComponent(tf3D_Rong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf3D_y)
                    .addComponent(tf3D_Dai)
                    .addComponent(tf3D_Cao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel3DInputLayout.setVerticalGroup(
            panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf3D_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf3D_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf3D_Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tf3D_Dai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panel3DInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf3D_Rong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf3D_Cao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel3DShape.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shape", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        bg3D.add(butSphere);
        butSphere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sphere.png"))); // NOI18N

        bg3D.add(butCube);
        butCube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cuboid.png"))); // NOI18N

        bg3D.add(butCone);
        butCone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cone.png"))); // NOI18N

        javax.swing.GroupLayout panel3DShapeLayout = new javax.swing.GroupLayout(panel3DShape);
        panel3DShape.setLayout(panel3DShapeLayout);
        panel3DShapeLayout.setHorizontalGroup(
            panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butCube, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3DShapeLayout.setVerticalGroup(
            panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DShapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butCone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3DShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(butSphere, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butCube, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        but3DPaint.setText("Paint");
        but3DPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3DPaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3DLayout = new javax.swing.GroupLayout(panel3D);
        panel3D.setLayout(panel3DLayout);
        panel3DLayout.setHorizontalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3DLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(but3DPaint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(panel3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panel3DInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel3DLayout.setVerticalGroup(
            panel3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3DLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel3DInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3DShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(but3DPaint)
                .addGap(19, 19, 19))
        );

        panelSetUp.add(panel3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        panelObj.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        panelTransform.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transform", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel10.setText("X:");

        jLabel14.setText("Y:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Góc");

        bgObject.add(butMove);
        butMove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Move.png"))); // NOI18N

        bgObject.add(butScaling);
        butScaling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/scale.png"))); // NOI18N

        bgObject.add(butRotation);
        butRotation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/refresh.png"))); // NOI18N

        bgObject.add(butReflX);
        butReflX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reflectX.png"))); // NOI18N

        bgObject.add(butReflY);
        butReflY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reflectY.png"))); // NOI18N

        bgObject.add(butReflO);
        butReflO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reflectO.png"))); // NOI18N

        javax.swing.GroupLayout panelTransformLayout = new javax.swing.GroupLayout(panelTransform);
        panelTransform.setLayout(panelTransformLayout);
        panelTransformLayout.setHorizontalGroup(
            panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransformLayout.createSequentialGroup()
                        .addComponent(butMove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butScaling, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransformLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNewCorner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransformLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(tfNewX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNewY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransformLayout.createSequentialGroup()
                        .addComponent(butReflX, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butReflY, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butReflO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelTransformLayout.setVerticalGroup(
            panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNewX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfNewY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNewCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butRotation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butScaling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butReflY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butReflX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butReflO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComponent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Component", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        butShowCo.setText("Show Coordinates");
        butShowCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butShowCoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComponentLayout = new javax.swing.GroupLayout(panelComponent);
        panelComponent.setLayout(panelComponentLayout);
        panelComponentLayout.setHorizontalGroup(
            panelComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(butShowCo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelComponentLayout.setVerticalGroup(
            panelComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butShowCo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        butTransform.setText("Paint");
        butTransform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTransformActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelObjLayout = new javax.swing.GroupLayout(panelObj);
        panelObj.setLayout(panelObjLayout);
        panelObjLayout.setHorizontalGroup(
            panelObjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addComponent(panelComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransform, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelObjLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butTransform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelObjLayout.setVerticalGroup(
            panelObjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butTransform, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSetUp.add(panelObj, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        lbCoAni.setColumns(20);
        lbCoAni.setRows(5);
        jScrollPane2.setViewportView(lbCoAni);

        javax.swing.GroupLayout panelAniLayout = new javax.swing.GroupLayout(panelAni);
        panelAni.setLayout(panelAniLayout);
        panelAniLayout.setHorizontalGroup(
            panelAniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        panelAniLayout.setVerticalGroup(
            panelAniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        panelSetUp.add(panelAni, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        javax.swing.GroupLayout panelDrawingLayout = new javax.swing.GroupLayout(panelDrawing);
        panelDrawing.setLayout(panelDrawingLayout);
        panelDrawingLayout.setHorizontalGroup(
            panelDrawingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDrawingLayout.createSequentialGroup()
                .addComponent(panelSetUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDrawingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDrawingLayout.setVerticalGroup(
            panelDrawingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDrawingLayout.createSequentialGroup()
                .addGroup(panelDrawingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDrawingArea, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(panelSetUp, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelOperation.setBackground(new java.awt.Color(0, 0, 0));
        panelOperation.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        butOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Open File.png"))); // NOI18N
        butOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOpenFileActionPerformed(evt);
            }
        });

        butSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperationLayout = new javax.swing.GroupLayout(panelOperation);
        panelOperation.setLayout(panelOperationLayout);
        panelOperationLayout.setHorizontalGroup(
            panelOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperationLayout.createSequentialGroup()
                .addComponent(butOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperationLayout.setVerticalGroup(
            panelOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(butOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(butSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTool.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tools", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        cbCustomLine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT", "DASH", "DOT", "DASHDOT", "DASHDOTDOT", "ARROW" }));

        butClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Clean.png"))); // NOI18N
        butClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCleanActionPerformed(evt);
            }
        });

        cbCoordinate.setText("Coordinate");
        cbCoordinate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbCoordinateStateChanged(evt);
            }
        });
        cbCoordinate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbCoordinateFocusLost(evt);
            }
        });
        cbCoordinate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCoordinateActionPerformed(evt);
            }
        });

        cbGrid.setText("Gridline");
        cbGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGridActionPerformed(evt);
            }
        });

        bg_.add(rb2D);
        rb2D.setText("2D");
        rb2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2DActionPerformed(evt);
            }
        });

        bg_.add(rb3D);
        rb3D.setText("3D");
        rb3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3DActionPerformed(evt);
            }
        });

        butColour.setFont(new java.awt.Font("Tahoma", 0, 5)); // NOI18N
        butColour.setText("Color");
        butColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butColourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelToolLayout = new javax.swing.GroupLayout(panelTool);
        panelTool.setLayout(panelToolLayout);
        panelToolLayout.setHorizontalGroup(
            panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butClean, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butColour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbCustomLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbCoordinate)
                .addGap(18, 18, 18)
                .addComponent(cbGrid)
                .addGap(18, 18, 18)
                .addComponent(rb2D)
                .addGap(18, 18, 18)
                .addComponent(rb3D)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelToolLayout.setVerticalGroup(
            panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butColour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butClean, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCustomLine, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCoordinate)
                        .addComponent(cbGrid)
                        .addComponent(rb2D)
                        .addComponent(rb3D)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelObject.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Object", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        butTruck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/car.png"))); // NOI18N
        butTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTruckActionPerformed(evt);
            }
        });

        butWindmill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/windmill .png"))); // NOI18N
        butWindmill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butWindmillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelObjectLayout = new javax.swing.GroupLayout(panelObject);
        panelObject.setLayout(panelObjectLayout);
        panelObjectLayout.setHorizontalGroup(
            panelObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butWindmill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelObjectLayout.setVerticalGroup(
            panelObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butWindmill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAnimation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        butAnimationTruck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/car.png"))); // NOI18N
        butAnimationTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnimationTruckActionPerformed(evt);
            }
        });

        butPlayStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/play.png"))); // NOI18N
        butPlayStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPlayStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAnimationLayout = new javax.swing.GroupLayout(panelAnimation);
        panelAnimation.setLayout(panelAnimationLayout);
        panelAnimationLayout.setHorizontalGroup(
            panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butAnimationTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPlayStop, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAnimationLayout.setVerticalGroup(
            panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butPlayStop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAnimationTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addComponent(panelTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelObject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAnimation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDrawing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDrawing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    boolean constraint2D() {
        String x1 = tf2D_SX.getText();
        String y1 = tf2D_SY.getText();
        String x2 = tf2D_EX.getText();
        String y2 = tf2D_EY.getText();
        if (x1.equals("") || y1.equals("") || x2.equals("") || y2.equals("")) {
            return false;
        }
        return true;
    }
    
    boolean constraint3D() {
        String x = tf3D_X.getText();
        String y = tf3D_y.getText();
        String z = tf3D_Z.getText();
        String dai = tf3D_Dai.getText();
        String rong = tf3D_Rong.getText();
        String cao = tf3D_Cao.getText();
        if (x.equals("") ||y.equals("") ||z.equals("") || dai.equals("") || rong.equals("") || cao.equals("")) {
            return false;
        }
        return true;
    }
    
    boolean constraintObj(){
        String x = tfNewX.getText();
        String y = tfNewY.getText();
        String angles = tfNewCorner.getText();
        if (x.equals("") ||y.equals("") || angles.equals("")) {
            return false;
        }
        return true;
    }
    
    private void rb2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2DActionPerformed
        panel2D.setVisible(true);
        panel3D.setVisible(false);
        panelObj.setVisible(false);
        panelAni.setVisible(false);
        if(cbCoordinate.isSelected()){
            repaint();
        }
    }//GEN-LAST:event_rb2DActionPerformed

    private void rb3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3DActionPerformed
        panel2D.setVisible(false);
        panel3D.setVisible(true);
        panelObj.setVisible(false);
        panelAni.setVisible(false);        
        panelDrawingArea.repaint();
        if(cbCoordinate.isSelected()){
            repaint();
        }
        
    }//GEN-LAST:event_rb3DActionPerformed

    private void cbCoordinateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCoordinateActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_cbCoordinateActionPerformed

    private void cbCoordinateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbCoordinateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCoordinateFocusLost

    private void cbCoordinateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbCoordinateStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCoordinateStateChanged

    private void butColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butColourActionPerformed
        color = JColorChooser.showDialog(this, "Choose Color ", Color.white);
        butColour.setBackground(color);
    }//GEN-LAST:event_butColourActionPerformed

    private void butOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOpenFileActionPerformed
        JFileChooser fileChooser = new JFileChooser(new File("c:\\"));
        fileChooser.setDialogTitle("Choose a file");
        fileChooser.setFileFilter(new FileNameExtensionFilter("image", "png"));
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "Chose file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String pathFile = file.getAbsolutePath().replace("//", "--");
            try {
                paintComponent(panelDrawingArea.getGraphics(),new ImageIcon(pathFile));
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_butOpenFileActionPerformed

    public void paintComponent(Graphics g, ImageIcon icon) {
//        super.paintComponent(g);
        Dimension d = panelDrawingArea.getSize();
        g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
        setOpaque(false);
    }
 

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
        JFileChooser fileSave = new JFileChooser(new File("c:\\"));
        fileSave.setDialogTitle("Save a file");
        fileSave.setFileFilter(new FileNameExtensionFilter("image", "png"));
        int result = fileSave.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            BufferedImage image = new BufferedImage(panelDrawingArea.getWidth(),panelDrawingArea.getHeight(), BufferedImage.TYPE_INT_RGB);
            File file = fileSave.getSelectedFile();
            String fileName = file.getAbsolutePath();
            try {
                File img = new File(fileName);
                ImageIO.write(image, "png", file);
            } catch (Exception e) {
            }
        } 
    }//GEN-LAST:event_butSaveActionPerformed

    private void but2DPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2DPaintActionPerformed
        if(constraint2D()== true){
            start = new Point();
            end = new Point();
            start.x = ConvertX(Integer.parseInt(tf2D_SX.getText()));
            start.y = ConvertY(Integer.parseInt(tf2D_SY.getText()));
            end.x = ConvertX(Integer.parseInt(tf2D_EX.getText()));
            end.y = ConvertY(Integer.parseInt(tf2D_EY.getText()));
            repaint();
        }
        else{
            JOptionPane.showMessageDialog(this,"Vui lòng điển đủ tọa độ" );
        }
    }//GEN-LAST:event_but2DPaintActionPerformed

    private void panelDrawingAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawingAreaMouseClicked

    }//GEN-LAST:event_panelDrawingAreaMouseClicked

    private void panelDrawingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDrawingMouseClicked

    }//GEN-LAST:event_panelDrawingMouseClicked

    private void cbGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGridActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_cbGridActionPerformed

    private void but3DPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3DPaintActionPerformed
        repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_but3DPaintActionPerformed

    private void butTransformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTransformActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_butTransformActionPerformed

    private void butWindmillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butWindmillActionPerformed
        panelObj.setVisible(true);
        panel2D.setVisible(false);
        panel3D.setVisible(false);
        object = "Windmill";
        dialogWindmill.setSize(240, 220);
        dialogWindmill.setLocationRelativeTo(null);
        dialogWindmill.setVisible(true);   
    }//GEN-LAST:event_butWindmillActionPerformed

    private void butCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCleanActionPerformed
        panelDrawingArea.removeAll();
        panelDrawingArea.repaint();
        tf2D_EX.setText("");
        tf2D_EY.setText("");
        tf2D_SX.setText("");
        tf2D_SY.setText("");
        tf3D_Cao.setText("");
        tf3D_Dai.setText("");
        tf3D_Rong.setText("");
        tf3D_X.setText("");
        tf3D_Z.setText("");
        tf3D_y.setText("");
        tfNewCorner.setText("");
        tfNewX.setText("");
        tfNewY.setText("");
        tfOX.setText("");
        tfOY.setText("");
        tfSize.setText("");
        object = "";
        bg2D.clearSelection();
        bg3D.clearSelection();
        bgObject.clearSelection();
        cbCoordinate.setSelected(false);
        cbGrid.setSelected(false);
    }//GEN-LAST:event_butCleanActionPerformed

    private void butTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTruckActionPerformed
        // TODO add your handling code here:
        panelObj.setVisible(true);
        panel2D.setVisible(false);
        panel3D.setVisible(false);
        object = "Truck";
        dialogTruck.setSize(240, 220);
        dialogTruck.setLocationRelativeTo(null);
        dialogTruck.setVisible(true);        
    }//GEN-LAST:event_butTruckActionPerformed

    private void butPaintTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPaintTruckActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(tfSize.getText())<40){
            JOptionPane.showMessageDialog(panelComponent, "Kích thước xe quá nhỏ", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Point tr = new Point(ConvertX(Integer.parseInt(tfOX.getText())), ConvertY(Integer.parseInt(tfOY.getText())));
        t = new Truck(tr, Integer.parseInt(tfSize.getText()), size);
        t.init();
        t.draw(panelDrawingArea.getGraphics());
        dialogTruck.dispose();
        
        // Hiển thị tọa độ
        lbHienThiThongTin.setText(t.showCoor());
    }//GEN-LAST:event_butPaintTruckActionPerformed

    private void butAnimationTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnimationTruckActionPerformed
        // TODO add your handling code here:
        panel2D.setVisible(false);
        panel3D.setVisible(false);
        panelObj.setVisible(false);
        butPlayStop.setEnabled(true);
        panelAni.setVisible(true);
        
        if(running){
            ani.play(panelDrawingArea, panelDrawingArea.getGraphics(), angle, speed, 0);
            angle+= 30;
            flag +=10;
            if(flag > panelDrawingArea.getWidth()){
                time.stop();
                running = false;
                changePlayStop();
            }
        }else{
            ani.init(panelDrawingArea);
            ani.play(panelDrawingArea, panelDrawingArea.getGraphics(), 0, 0, 0);
        }
        lbCoAni.setText(ani.showCoor());
    }//GEN-LAST:event_butAnimationTruckActionPerformed

    private void butPlayStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPlayStopActionPerformed
        // TODO add your handling code here:
        if(running==false){
            running = true;
            speed= 10;
            if(flag > panelDrawingArea.getWidth()){
                ani.init(panelDrawingArea);
                flag =0;
            }
            time = new Timer(delay, butAnimationTruck.getActionListeners()[0]);
            time.start();
        }else if (running){
            running = false;
            time.stop();
        }
        changePlayStop();
    }//GEN-LAST:event_butPlayStopActionPerformed
    void changePlayStop() {
        if (running) {
            butPlayStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/stop.png")));
        } else if (!running) {
            butPlayStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/play.png")));
        }
    }
    private void butPaintWmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPaintWmActionPerformed
        // TODO add your handling code here:
        Point wmill = new Point(ConvertX(Integer.parseInt(tfOXWm.getText())), ConvertY(Integer.parseInt(tfOYWm.getText())));
        this.wm = new Windmill(wmill, size, Integer.parseInt(tfSizeWm.getText()), color);
        this.wm.init();
        this.wm.draw(panelDrawingArea.getGraphics());
        
        // Hiển thị tọa độ
        lbHienThiThongTin.setText(wm.showCoor());
        dialogWindmill.dispose();
    }//GEN-LAST:event_butPaintWmActionPerformed

    private void butShowCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butShowCoActionPerformed
        // TODO add your handling code here:
        dialogCoor.setLocationRelativeTo(null);
        dialogCoor.setSize(430, 520);
        dialogCoor.setVisible(true);
    }//GEN-LAST:event_butShowCoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg2D;
    private javax.swing.ButtonGroup bg3D;
    private javax.swing.ButtonGroup bgObject;
    private javax.swing.ButtonGroup bg_;
    private javax.swing.JButton but2DPaint;
    private javax.swing.JButton but3DPaint;
    private javax.swing.JButton butAnimationTruck;
    private javax.swing.JToggleButton butCircle;
    private javax.swing.JButton butClean;
    private javax.swing.JButton butColour;
    private javax.swing.JToggleButton butCone;
    private javax.swing.JToggleButton butCube;
    private javax.swing.JToggleButton butEllipse;
    private javax.swing.JToggleButton butLine;
    private javax.swing.JToggleButton butMove;
    private javax.swing.JButton butOpenFile;
    private javax.swing.JButton butPaintTruck;
    private javax.swing.JButton butPaintWm;
    private javax.swing.JButton butPlayStop;
    private javax.swing.JToggleButton butRectangle;
    private javax.swing.JToggleButton butReflO;
    private javax.swing.JToggleButton butReflX;
    private javax.swing.JToggleButton butReflY;
    private javax.swing.JToggleButton butRotation;
    private javax.swing.JButton butSave;
    private javax.swing.JToggleButton butScaling;
    private javax.swing.JButton butShowCo;
    private javax.swing.JToggleButton butSphere;
    private javax.swing.JButton butTransform;
    private javax.swing.JToggleButton butTriangle;
    private javax.swing.JButton butTruck;
    private javax.swing.JButton butWindmill;
    private javax.swing.JCheckBox cbCoordinate;
    private javax.swing.JComboBox<String> cbCustomLine;
    private javax.swing.JCheckBox cbGrid;
    private javax.swing.JDialog dialogCoor;
    private javax.swing.JDialog dialogTruck;
    private javax.swing.JDialog dialogWindmill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea lbCoAni;
    private javax.swing.JTextArea lbHienThiThongTin;
    private javax.swing.JPanel panel2D;
    private javax.swing.JPanel panel2DEnd;
    private javax.swing.JPanel panel2DShape;
    private javax.swing.JPanel panel2DStart;
    private javax.swing.JPanel panel3D;
    private javax.swing.JPanel panel3DInput;
    private javax.swing.JPanel panel3DShape;
    private javax.swing.JPanel panelAni;
    private javax.swing.JPanel panelAnimation;
    private javax.swing.JPanel panelComponent;
    private javax.swing.JPanel panelDrawing;
    private javax.swing.JPanel panelDrawingArea;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelObj;
    private javax.swing.JPanel panelObject;
    private javax.swing.JPanel panelOperation;
    private javax.swing.JPanel panelSetUp;
    private javax.swing.JPanel panelTool;
    private javax.swing.JPanel panelTransform;
    private javax.swing.JPanel panelTruck;
    private javax.swing.JPanel panelWindmill;
    private javax.swing.JRadioButton rb2D;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JTextField tf2D_EX;
    private javax.swing.JTextField tf2D_EY;
    private javax.swing.JTextField tf2D_SX;
    private javax.swing.JTextField tf2D_SY;
    private javax.swing.JTextField tf3D_Cao;
    private javax.swing.JTextField tf3D_Dai;
    private javax.swing.JTextField tf3D_Rong;
    private javax.swing.JTextField tf3D_X;
    private javax.swing.JTextField tf3D_Z;
    private javax.swing.JTextField tf3D_y;
    private javax.swing.JTextField tfNewCorner;
    private javax.swing.JTextField tfNewX;
    private javax.swing.JTextField tfNewY;
    private javax.swing.JTextField tfOX;
    private javax.swing.JTextField tfOXWm;
    private javax.swing.JTextField tfOY;
    private javax.swing.JTextField tfOYWm;
    private javax.swing.JTextField tfSize;
    private javax.swing.JTextField tfSizeWm;
    // End of variables declaration//GEN-END:variables

    private void setOpaque(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
